### ISSUE TITLE
drive_start_yard_line str formatting

### ISSUE THREAD

**Issue by nickwan** [nflverse/nflverse-pbp#25]
the column `drive_start_yard_line` has some inconsistencies between `yrdln`: 

```['50', '', 'WAS20', 'NYJ20', 'ATL20']```
where the format from `yrdln` is three-letter-abbr and the yard line with a space in between. 

the column `drive_start_yard_line` also has a few inconsistencies, albeit much smaller: 
```['50', '']```

obviously there's an easy bandage to fix this, but unsure if the str formatting in the processing pipeline is truncating strings for some reason

**Comment by guga31bb** [comment]
The drive variables are mostly us passing along info provided by nfl in the
data, so I'm guessing that's the actual values, but can check later. We
haven't paid a lot of attention to the drive stuff because it's extremely
buggy on nfl's end
