### ISSUE TITLE
`stat_type` argument in `load_player_stats()` yields unexpected results

### ISSUE THREAD

**Issue by gacolitti** [nflverse/nflverse-pbp#75]
I see a few kickers included in the "offense" stat type, but not all of them. This is weird because kicking seems like an offensive position, and there is also a "kicking" `stat_type` option.

```r
library(nflreadr)
library(dplyr)

kicking <- load_player_stats(seasons = TRUE, stat_type = "kicking")
offense <- load_player_stats(seasons = TRUE, stat_type = "offense")
glimpse(semi_join(offense, kicking))
```
Also, I see defensive players in the "offense" stat type, and there is no option for `stat_type = "defense"`:

```r
offense %>% 
  distinct(player_display_name, position) %>% 
  filter(player_display_name == "J.J. Watt")
```

What am I missing?

Thanks for all the work on this project!

**Comment by tanho63** [comment]
`stat_type` refers to the particular statistics returned, not which players are returned - so kickers appearing in offense stat refers to those players accumulating rushing/receiving/passing stats. defensive player stats aren't yet supported via nflreadr but is on our to-do list

**Comment by gacolitti** [comment]
Got it. Thanks @tanho63!
