### ISSUE TITLE
Missing Schedule data for 2022 and 2023

### ISSUE THREAD

**Issue by Games3D** [nflverse/nflverse-pbp#82]
Missing the 2022 and 2023 data in schedules.

I see that your data has moved to https://github.com/nflverse/nflverse-data/releases but i'm still not seeing it over there either.

This is needed to allow for sportsdataverse.nfl.load_nfl_rosters(seasons=2023, return_as_pandas=True) to work.

**Comment by tanho63** [comment]
Both schedules and rosters are returning data, so this looks like an issue to file in the repo for whatever package you were using 
![4D5DCCE6-3266-42F2-85AD-E8C1A452260E](https://github.com/nflverse/nflverse-pbp/assets/38083823/b422aa5e-4e6d-43fa-aa1d-e2fdba9d4b12)

**Comment by Games3D** [comment]
Thank you very much for the quick reply, ill reach out to the maintainers of the other repo.
